In [126]:
import PIL as pillow
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
import os
import pandas as pd
#np.random.seed(123)  # for reproducibility

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.utils import np_utils
from keras.datasets import mnist



In [10]:
im=Image.open("Biwa Ko.jpg").convert("L")
imarr=np.array(im)
flatim=imarr.flatten('F')
flatim

array([46, 46, 46, ..., 27, 27, 27], dtype=uint8)

In [31]:
#!! pip install opencv-python

In [2]:
from keras.datasets import mnist

x = mnist.load_data()

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
x#[1][0][1][1]
# this is the keras dataset

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [4]:
import cv2

In [30]:
img=cv2.imread("Biwa Ko.jpg")
img.shape

(400, 640, 3)

In [55]:
img=cv2.imread("Biwa Ko.jpg")
#img = img.reshape(img.shape[0], 400, 640, 3)
img.reshape(1,400,640,3)
img = img/255
img

array([[[0.20784314, 0.21176471, 0.10980392],
        [0.20784314, 0.21176471, 0.10980392],
        [0.20784314, 0.21176471, 0.10980392],
        ...,
        [0.18039216, 0.17647059, 0.07843137],
        [0.18039216, 0.17647059, 0.07843137],
        [0.18039216, 0.17647059, 0.07843137]],

       [[0.20784314, 0.21176471, 0.10980392],
        [0.20784314, 0.21176471, 0.10980392],
        [0.20784314, 0.21176471, 0.10980392],
        ...,
        [0.18039216, 0.17647059, 0.07843137],
        [0.18039216, 0.17647059, 0.07843137],
        [0.18039216, 0.17647059, 0.07843137]],

       [[0.20784314, 0.21176471, 0.10980392],
        [0.20784314, 0.21176471, 0.10980392],
        [0.20784314, 0.21176471, 0.10980392],
        ...,
        [0.18039216, 0.17647059, 0.07843137],
        [0.18039216, 0.17647059, 0.07843137],
        [0.18039216, 0.17647059, 0.07843137]],

       ...,

       [[0.17647059, 0.17254902, 0.07058824],
        [0.17647059, 0.17254902, 0.07058824],
        [0.17647059, 0

#### img = img.reshape(img.shape[0], 400, 28, 1)


In [127]:
# list_of_lakes = ['Biwa Ko.jpg', 'Black Lake.jpg']
list_of_img = []
list_of_names = []
path = '/Users/tovahirsch/Desktop/Capstone/Pics/'
for filename in os.listdir(path=path):
    if '.jpg' in filename:
        list_of_names.append(filename)
#         img=cv2.imread(path + filename, 0)
#         img = img/255
#         list_of_img.append(img)
#     break
pd.DataFrame(list_of_names).to_csv('image_checklist.c')

0
0                 Aberdeen Lake.jpg
1                    Airag Lake.jpg
2                   Aishik Lake.jpg
3                     Akkajaure.jpg
4                        Alakol.jpg
5                  Alesayqin Ha.jpg
6                 Amadjuak Lake.jpg
7      American Falls Reservoir.jpg
8             Amistad Reservoir.jpg
9                   Aqqikkol Hu.jpg
10                     Aral Sea.jpg
11               Ataturk Barajt.jpg
12                      Aursund.jpg
13                   Ayakkum Hu.jpg
14                   Aydar Ko‘l.jpg
15                  Aylmer Lake.jpg
16                       Åsnen.jpg
17             Baidagang Shuiku.jpg
18                   Baker Lake.jpg
19                  Banggong Co.jpg
20                       Bariri.jpg
21                 Barra Bonita.jpg
22           Barragem Itumbiara.jpg
23                    Bear Lake.jpg
24                     Beysehir.jpg
25             Bhadra Reservoir.jpg
26           Bhumphol K. K. Nam.jpg
27              Big Rideau Lake.jpg
28               Big Trout Lake.jpg
29                      Biwa Ko.jpg
..                              ...
636             Vanderkloof Dam.jpg
637                     Vänern.jpg
638                    Vättern.jpg
639            Vilyuy Reservoir.jpg
640                   Virihaure.jpg
641         Volgograd Reservoir.jpg
642          Votkinsk Reservoir.jpg
643                 Võrtsjärv.jpg
644  Walter F. George Reservoir.jpg
645               Washburn Lake.jpg
646                  Weishan Hu.jpg
647                Wheeler Lake.jpg
648               Whitefish Bay.jpg
649               Wholdaia Lake.jpg
650              Williston Lake.jpg
651              Wollaston Lake.jpg
652                  Wuchang Hu.jpg
653          Wyangala Reservoir.jpg
654           Xinanjiang Shuiku.jpg
655         Xinfengjiang Shuiku.jpg
656                Yamzho Yumco.jpg
657               Yathkyed Lake.jpg
658            Yellowstone Lake.jpg
659                       Yeren.jpg
660                    Yke Lake.jpg
661                Yueliang Pao.jpg
662               Zalew Wislany.jpg
663                   Zeta Lake.jpg
664              Zeya Reservoir.jpg
665                Zhalauly Kli.jpg

[666 rows x 1 columns]

In [124]:
list_of_img[0]

array([[0.05882353, 0.06666667, 0.06666667, ..., 0.61568627, 0.56862745,
        0.59607843],
       [0.05882353, 0.06666667, 0.06666667, ..., 0.61568627, 0.46666667,
        0.49019608],
       [0.05882353, 0.05882353, 0.05882353, ..., 0.61568627, 0.53333333,
        0.39607843],
       ...,
       [0.09411765, 0.09411765, 0.09411765, ..., 0.02745098, 0.02745098,
        0.02745098],
       [0.09411765, 0.09411765, 0.09411765, ..., 0.02745098, 0.02745098,
        0.02745098],
       [0.09411765, 0.09411765, 0.09411765, ..., 0.02745098, 0.02745098,
        0.02745098]])

In [105]:
#set up model
model = Sequential()

model.add(Convolution2D(filters = 6, kernel_size = 3, activation='relu', input_shape=(400,640,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Convolution2D(16, kernel_size = 3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

In [106]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_42 (Conv2D)           (None, 398, 638, 6)       168       
_________________________________________________________________
max_pooling2d_37 (MaxPooling (None, 199, 319, 6)       0         
_________________________________________________________________
conv2d_43 (Conv2D)           (None, 197, 317, 16)      880       
_________________________________________________________________
max_pooling2d_38 (MaxPooling (None, 98, 158, 16)       0         
_________________________________________________________________
dropout_37 (Dropout)         (None, 98, 158, 16)       0         
_________________________________________________________________
flatten_21 (Flatten)         (None, 247744)            0         
_________________________________________________________________
dense_38 (Dense)             (None, 128)               31711360  
__________

In [107]:
# 6. Compile model
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [96]:
img.shape

(400, 640, 3)

In [99]:
imgs = np.array([img])
imgs.shape

(1, 400, 640, 3)

In [108]:
#### 7. Fit model on training data
model.fit(imgs,np.array([[0]]), batch_size=32, epochs=10, verbose=1)

Epoch 1/10


KeyboardInterrupt: 

In [11]:
# for x, y in zip(list_of_img, list_of_y):
#     model.fit(x, y, 
#           batch_size=32, epochs=10, verbose=1)

SyntaxError: unexpected EOF while parsing (<ipython-input-11-248255bab3d7>, line 1)

In [ ]:
'''cv2.normalize(img, img, 0, 255, cv2.NORM_MINMAX)

    cv2.imshow('dst_rt', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    li.append(img)'''

In [ ]:
#img = cv2.resize(img, (800, 800))
cv2.normalize(img, img, 0, 255, cv2.NORM_MINMAX)
img

In [ ]:
cv2.imshow('dst_rt', img)
img

In [ ]:
cv2.waitKey(0)

In [ ]:
cv2.destroyAllWindows()

In [ ]:
img

In [51]:
img2=cv2.imread('Black Lake.jpg',0)
img2.shape

(400, 640)

# How do I use this array and transform it so that it has x and y which can then be pushed into the format as exist in mnist.load_data()

In [35]:
img.shape

(400, 640)

In [49]:
img[4].shape

(640,)

In [ ]:
plt.imshow(digits.images[-5], cmap=plt.cm.gray_r, interpolation='nearest')